/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Book({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/aRPlbEK5wvx8ooaw/scene.splinecode",
  );
  return (
    <>
      <color attach="background" args={["#f1f0e3"]} />
      <fog attach="fog" args={["#f1f0e3", 1230.869, 2000]} />
      <group {...props} dispose={null}>
        <scene name="Scene">
          <group
            name="Group 3"
            position={[99.82, 189.81, 240.32]}
            rotation={[0, 0, 1.58]}
            scale={[0.81, 1, 0.98]}
          >
            <mesh
              name="Shape"
              geometry={nodes.Shape.geometry}
              material={materials["Shape Material"]}
              castShadow
              receiveShadow
              position={[-53.08, -158.75, -252.59]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={materials["Cylinder Material"]}
              castShadow
              receiveShadow
              position={[2.84, -157.3, -0.52]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <group
              name="Group 2"
              position={[24.46, -165.56, -0.69]}
              rotation={[Math.PI, 0, Math.PI / 2]}
            >
              <mesh
                name="Cube 2"
                geometry={nodes["Cube 2"].geometry}
                material={materials["Cube 2 Material"]}
                castShadow
                receiveShadow
                position={[-189.31, -22.88, -1.39]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
              />
              <mesh
                name="Cube"
                geometry={nodes.Cube.geometry}
                material={materials["Cube Material"]}
                castShadow
                receiveShadow
                position={[-187.21, 1.75, 0.2]}
              />
              <mesh
                name="Shape1"
                geometry={nodes.Shape1.geometry}
                material={materials["Shape1 Material"]}
                castShadow
                receiveShadow
                position={[-3.21, 21.55, -249.8]}
              />
            </group>
            <group
              name="Group"
              position={[-22.94, -166.56, 4]}
              rotation={[0, 0, -Math.PI / 2]}
            >
              <mesh
                name="Cube1"
                geometry={nodes.Cube1.geometry}
                material={materials["Cube1 Material"]}
                castShadow
                receiveShadow
                position={[-188.38, -25.24, -5.62]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                name="Cube2"
                geometry={nodes.Cube2.geometry}
                material={materials["Cube2 Material"]}
                castShadow
                receiveShadow
                position={[-188.25, 1.75, -5.3]}
              />
              <mesh
                name="Shape2"
                geometry={nodes.Shape2.geometry}
                material={materials["Shape2 Material"]}
                castShadow
                receiveShadow
                position={[-3.21, 21.23, -255.3]}
              />
            </group>
          </group>
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[200, 300, 300]}
          />
          <OrthographicCamera
            name="1"
            makeDefault={true}
            far={10000}
            near={-50000}
          />
          <hemisphereLight
            name="Default Ambient Light"
            intensity={0.75}
            color="#eaeaea"
          />
        </scene>
      </group>
    </>
  );
}
